name: flutter_learn
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  #States
  flutter_bloc: ^8.1.1
  
  #Network
  http: ^0.13.5

  #Core
  equatable: ^2.0.3
  encrypt: ^5.0.1
  fluttertoast: ^8.0.9

  #Google
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  
  #Custom package
  fellow:
    path: ../fellow


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
